### ISSUE TITLE
undefined method `results_as_hash=' and 'results_as_hash'

### ISSUE THREAD

**Issue by whysthatso** [janko/sequel-activerecord_connection#22]
i'm running an app that i mostly developed on sqlite3 without problems, and want to migrate it to postgresql. i'm getting this error both in the development and production rails environment, right upon first interaction with the RodauthApp. I've also replicated the issue in the rails console when trying to create a user, or really doing anything involving the database.

At the same time i can interact with the database normally for all other Rails functionality, i.e. query for models, see schema etc.

any idea where this comes from?

stacktrace from  a docker-compose run
```
wp_admin  | /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection/utils.rb:9:in `ensure in set_value': undefined method `results_as_hash=' for #<PG::Connection:0x00007f0c25b531b8 host=db port=5432 user=wpadmin type_map_for_results=#<PG::TypeMapByOid:0x00007f0c25b35fc8> type_map_for_queries=#<PG::TypeMapByClass:0x00007f0c25b37da0>> (NoMethodError)
wp_admin  | 
wp_admin  |         object.send(:"#{name}=", original_value)
wp_admin  |               ^^^^^
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection/utils.rb:9:in `set_value'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection/sqlite.rb:26:in `block in _execute'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection/sqlite.rb:18:in `block in synchronize'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection.rb:38:in `block in synchronize'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection.rb:140:in `block (2 levels) in activerecord_lock'
wp_admin  |     from /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
wp_admin  |     from /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection.rb:139:in `block in activerecord_lock'
wp_admin  |     from /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
wp_admin  |     from /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
wp_admin  |     from /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
wp_admin  |     from /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection.rb:138:in `activerecord_lock'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection.rb:37:in `synchronize'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection/sqlite.rb:13:in `synchronize'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection/sqlite.rb:25:in `_execute'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/adapters/sqlite.rb:156:in `execute'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/dataset/actions.rb:1187:in `execute'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/adapters/sqlite.rb:364:in `fetch_rows'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/dataset/actions.rb:164:in `each'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/dataset/actions.rb:464:in `map'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/dataset/actions.rb:464:in `map'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/adapters/shared/sqlite.rb:499:in `parse_pragma'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/adapters/shared/sqlite.rb:541:in `schema_parse_table'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/database/query.rb:159:in `schema'
wp_admin  |     from /usr/local/bundle/bundler/gems/rodauth-9d34c8e7647c/lib/rodauth/features/base.rb:408:in `post_configure'
wp_admin  |     from /usr/local/bundle/bundler/gems/rodauth-9d34c8e7647c/lib/rodauth/features/email_base.rb:22:in `post_configure'
wp_admin  |     from /usr/local/bundle/bundler/gems/rodauth-9d34c8e7647c/lib/rodauth/features/internal_request.rb:337:in `post_configure'
wp_admin  |     from /usr/local/bundle/gems/rodauth-i18n-0.5.2/lib/rodauth/features/i18n.rb:27:in `post_configure'
wp_admin  |     from /usr/local/bundle/bundler/gems/rodauth-9d34c8e7647c/lib/rodauth.rb:62:in `configure'
wp_admin  |     from /usr/local/bundle/gems/roda-3.62.0/lib/roda.rb:296:in `plugin'
wp_admin  |     from /usr/local/bundle/gems/rodauth-rails-1.6.4/lib/rodauth/rails/app.rb:32:in `configure'
wp_admin  |     from /rails/app/misc/rodauth_app.rb:2:in `<class:RodauthApp>'
wp_admin  |     from /rails/app/misc/rodauth_app.rb:1:in `<top (required)>'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:30:in `require'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:30:in `require'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `cget'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `each'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `ls'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `each'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:296:in `block in eager_load_all'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `each'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `eager_load_all'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `instance_exec'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `run'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:60:in `run_initializers'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/application.rb:372:in `initialize!'
wp_admin  |     from /rails/config/environment.rb:5:in `<top (required)>'
wp_admin  |     from config.ru:3:in `require_relative'
wp_admin  |     from config.ru:3:in `block in <main>'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:312:in `block in start'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:379:in `handle_profiling'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:311:in `start'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:38:in `start'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:143:in `block in perform'
wp_admin  |     from <internal:kernel>:90:in `tap'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:134:in `perform'
wp_admin  |     from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
wp_admin  |     from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
wp_admin  |     from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<top (required)>'
wp_admin  |     from bin/rails:4:in `require'
wp_admin  |     from bin/rails:4:in `<main>'
wp_admin  | /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection

/utils.rb:5:in `set_value': undefined method `results_as_hash' for #<PG::Connection:0x00007f0c25b531b8 host=db port=5432 user=wpadmin type_map_for_results=#<PG::TypeMapByOid:0x00007f0c25b35fc8> type_map_for_queries=#<PG::TypeMapByClass:0x00007f0c25b37da0>> (NoMethodError)
wp_admin  | 
wp_admin  |         original_value = object.send(name)
wp_admin  |                                ^^^^^
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection/sqlite.rb:26:in `block in _execute'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection/sqlite.rb:18:in `block in synchronize'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection.rb:38:in `block in synchronize'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection.rb:140:in `block (2 levels) in activerecord_lock'
wp_admin  |     from /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
wp_admin  |     from /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection.rb:139:in `block in activerecord_lock'
wp_admin  |     from /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
wp_admin  |     from /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
wp_admin  |     from /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
wp_admin  |     from /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection.rb:138:in `activerecord_lock'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection.rb:37:in `synchronize'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection/sqlite.rb:13:in `synchronize'
wp_admin  |     from /usr/local/bundle/gems/sequel-activerecord_connection-1.2.9/lib/sequel/extensions/activerecord_connection/sqlite.rb:25:in `_execute'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/adapters/sqlite.rb:156:in `execute'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/dataset/actions.rb:1187:in `execute'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/adapters/sqlite.rb:364:in `fetch_rows'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/dataset/actions.rb:164:in `each'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/dataset/actions.rb:464:in `map'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/dataset/actions.rb:464:in `map'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/adapters/shared/sqlite.rb:499:in `parse_pragma'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/adapters/shared/sqlite.rb:541:in `schema_parse_table'
wp_admin  |     from /usr/local/bundle/gems/sequel-5.63.0/lib/sequel/database/query.rb:159:in `schema'
wp_admin  |     from /usr/local/bundle/bundler/gems/rodauth-9d34c8e7647c/lib/rodauth/features/base.rb:408:in `post_configure'
wp_admin  |     from /usr/local/bundle/bundler/gems/rodauth-9d34c8e7647c/lib/rodauth/features/email_base.rb:22:in `post_configure'
wp_admin  |     from /usr/local/bundle/bundler/gems/rodauth-9d34c8e7647c/lib/rodauth/features/internal_request.rb:337:in `post_configure'
wp_admin  |     from /usr/local/bundle/gems/rodauth-i18n-0.5.2/lib/rodauth/features/i18n.rb:27:in `post_configure'
wp_admin  |     from /usr/local/bundle/bundler/gems/rodauth-9d34c8e7647c/lib/rodauth.rb:62:in `configure'
wp_admin  |     from /usr/local/bundle/gems/roda-3.62.0/lib/roda.rb:296:in `plugin'
wp_admin  |     from /usr/local/bundle/gems/rodauth-rails-1.6.4/lib/rodauth/rails/app.rb:32:in `configure'
wp_admin  |     from /rails/app/misc/rodauth_app.rb:2:in `<class:RodauthApp>'
wp_admin  |     from /rails/app/misc/rodauth_app.rb:1:in `<top (required)>'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:30:in `require'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:30:in `require'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `cget'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `each'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `ls'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `each'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:296:in `block in eager_load_all'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `each'
wp_admin  |     from /usr/local/bundle/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `eager_load_all'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `instance_exec'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `run'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
wp_admin  |     from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:60:in `run_initializers'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/application.rb:372:in `initialize!'
wp_admin  |     from /rails/config/environment.rb:5:in `<top (required)>'
wp_admin  |     from config.ru:3:in `require_relative'
wp_admin  |     from config.ru:3:in `block in <main>'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:312:in `block in start'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:379:in `handle_profiling'
wp_admin  |     from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:311:in `start'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:38:in `start'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:143:in `block in perform'
wp_admin  |     from <internal:kernel>:90:in `tap'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:134:in `perform'
wp_admin  |     from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
wp_admin  |     from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
wp_admin  |     from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
wp_admin  |     from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<top (required)>'
wp_admin  |     from bin/rails:4:in `require'
wp_admin  |     from bin/rails:4:in `<main>'
wp_admin exited with code 1
```

**Comment by janko** [comment]
It seems you haven't updated the initialization of the Sequel database object to use the `postgres` adapter, so it's still trying to use the `sqlite` adapter with Active Record's Postgres connection, which is incompatible.

I will update the error message to make this clearer.

**Comment by whysthatso** [comment]
oh yes, that was it. thanks.
